[package]
authors = ["ClSlaid <cailue@bupt.edu.cn>"]
description = "[WIP] A DNS server supporting UDP, TCP, TLS and QUIC."
edition = "2021"
name = "tsein-dns"
version = "0.1.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
anyhow = "1.0.57"
rand = "0.8.5"
bytes = "1.1.0"
color-eyre = "0.6.1"
stretto = { version = "0.4.3", features = ["async"] }
quinn = "0.8.2"
thiserror = "1.0.31"
futures = "0.3.21"
rustls = "0.20.4"
rustls-pemfile = "1.0.0"
rustls-native-certs = "0.6.2"
tokio = { version = "1.18.2", features = ["full"] }
tokio-rustls = "0.23.4"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["std", "time", "fmt", "local-time"] }
