[package]
authors = ["ClSlaid <cailue@bupt.edu.cn>"]
description = "A DNS Server."
edition = "2021"
name = "tsein-dns"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
bytes = "1.1"
color-eyre = "0.6"
once_cell = "1.9.0"
thiserror = "1.0"
futures = "0.3.19"
tokio = { version = "1.15", features = ["full"] }
tracing = "0.1"
