condense_wildcard_suffixes = true
license_template_path = "license.template"

newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

imports_granularity = "Crate"
imports_indent = "Block"
group_imports = "StdExternalCrate"